/*
 * (C) Copyright 2012
 *     wangflord@allwinnertech.com
 *
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program;
 *
 */
#ifndef __spare_head1_h__
#define __spare_head1_h__

#include "egon_def.h"

/* work mode */
#define WORK_MODE_PRODUCT (1 << 4)
#define WORK_MODE_UPDATE (1 << 5)

#define WORK_MODE_BOOT 0x00			//��������
#define WORK_MODE_USB_PRODUCT 0x10	//����USB����
#define WORK_MODE_CARD_PRODUCT 0x11 //���ڿ�����
#define WORK_MODE_USB_UPDATE 0x20	//����USB����
#define WORK_MODE_OUTER_UPDATE 0x21 //�����ⲿ������

#define UBOOT_MAGIC "uboot"
#define STAMP_VALUE 0x5F0A6C39
#define ALIGN_SIZE 8 * 1024

#define BOOT1_START_SECTOR_IN_SDMMC 38192
/******************************************************************************/
/*               the control information stored in file head                  */
/******************************************************************************/
struct spare_boot_ctrl_head
{
	unsigned int jump_instruction; // one intruction jumping to real code
	unsigned char magic[8];		   // ="u-boot"
	unsigned int check_sum;		   // generated by PC
	unsigned int align_size;	   // align size in byte
	unsigned int length;		   // the size of all file
	unsigned int uboot_length;	   // the size of uboot
	unsigned char version[8];	   // uboot version
	unsigned char platform[8];	   // platform information
	int reserved[1];			   //stamp space, 16bytes align
};

/******************************************************************************/
/*                          the data stored in file head                      */
/******************************************************************************/
struct spare_boot_data_head
{
	unsigned int dram_para[32];
	int run_clock;					 // Mhz
	int run_core_vol;				 // mV
	int uart_port;					 // UART���������
	normal_gpio_cfg uart_gpio[2];	 // UART������(���Դ�ӡ��)GPIO��Ϣ
	int twi_port;					 // TWI���������
	normal_gpio_cfg twi_gpio[2];	 // TWI������GPIO��Ϣ�����ڿ���TWI
	int work_mode;					 // ����ģʽ
	int storage_type;				 // �洢��������  0��nand   1��sdcard    2: spinor
	normal_gpio_cfg nand_gpio[32];	 // nand GPIO��Ϣ
	char nand_spare_data[256];		 // nand ������Ϣ
	normal_gpio_cfg sdcard_gpio[32]; // sdcard GPIO��Ϣ
	char sdcard_spare_data[256];	 // sdcard ������Ϣ
	int reserved[2];				 // ��������λ, 16bytes align
};

typedef struct spare_boot_head_t
{
	struct spare_boot_ctrl_head boot_head;
	struct spare_boot_data_head boot_data;
} uboot_file_head;

#endif
